const RPC_URL = 'https://rpc.quai.network/cyprus1';
const SCAN_URL = 'https://quaiscan.io/api';
const addressInput = document.querySelector('#address');
const observeButton = document.querySelector('#observe');
const state = document.querySelector('#state');
const error = document.querySelector('#error');
const selectorInput = document.querySelector('#selector');
const amountInput = document.querySelector('#amount');
const teachingOutput = document.querySelector('#teaching-output');
const connectWalletButton = document.querySelector('#connect-wallet');
const prepareRequestButton = document.querySelector('#prepare-request');
const signingOutput = document.querySelector('#signing-output');
const askInput = document.querySelector('#ask-quai');
const askButton = document.querySelector('#ask-button');
const askOutput = document.querySelector('#ask-output');
const cachedContractInput = document.querySelector('#cached-contract');
const cachedSelectorInput = document.querySelector('#cached-selector');
const rememberPatternButton = document.querySelector('#remember-pattern');
const comparePatternButton = document.querySelector('#compare-pattern');
const cacheOutput = document.querySelector('#cache-output');
const nftContractInput = document.querySelector('#nft-contract');
const nftTokenIdInput = document.querySelector('#nft-token-id');
const openNftButton = document.querySelector('#open-nft');
const findOthersButton = document.querySelector('#find-others');
const nftOutput = document.querySelector('#nft-output');
const runPolicyButton = document.querySelector('#run-policy');
const policyOutput = document.querySelector('#policy-output');
const issueLearnerButton = document.querySelector('#issue-learner');
const resetSandboxButton = document.querySelector('#reset-sandbox');
const sandboxOutput = document.querySelector('#sandbox-output');
const CACHE_KEY = 'bipu-known-operation-v1';
let connectedProvider = null;
let explainedRequest = null;

function isAddress(value) { return /^0x[a-fA-F0-9]{40}$/.test(value.trim()); }
function big(value) { return BigInt(value); }
function formatUnits(value, decimals = 18, places = 4) {
  const scale = 10n ** BigInt(decimals); const whole = value / scale;
  const fraction = (value % scale).toString().padStart(decimals, '0').slice(0, places).replace(/0+$/, '');
  return `${whole.toLocaleString()}${fraction ? `.${fraction}` : ''}`;
}
function shortAddress(value) { return `${value.slice(0, 8)}…${value.slice(-6)}`; }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char])); }
const WQUAI_CONTRACT = '0x006C3e2AaAE5DB1bCd11A1a097cE572312EADdBB';
function readCandidate() { const selector = selectorInput.value.trim().toLowerCase(); const amount = Number(amountInput.value); return { selector, amount: Number.isFinite(amount) && amount > 0 ? amount : 0 }; }
function explanation(candidate) {
  const known = candidate.selector === '0x2e1a7d4d' && candidate.amount > 0;
  return { known, amount: candidate.amount, title: known ? 'Withdraw WQUAI into native QUAI' : 'Unknown operation — re-understand required', intent: known ? `Convert ${candidate.amount} WQUAI into ${candidate.amount} native QUAI.` : 'The selector does not match the known WQUAI withdraw pattern.', why: known ? 'The contract burns or releases the wrapped representation and returns the underlying native asset to the caller.' : 'A selector alone is not enough to infer intent. The contract, method, and expected effect must match.', expected: known ? `WQUAI −${candidate.amount} · QUAI +${candidate.amount} · gas reserved` : 'No state change prediction is safe.', contract: WQUAI_CONTRACT, selector: candidate.selector };
}
function renderExplanation() { const result = explanation(readCandidate()); teachingOutput.innerHTML = `<div class="explanation-card ${result.known ? 'known' : 'unknown'}"><div class="explanation-status">${result.known ? 'RECOGNIZED PATTERN' : 'UNDERSTANDING BLOCKED'}</div><h3>${result.title}</h3><div class="explanation-grid"><div><span>INTENT</span><strong>${result.intent}</strong></div><div><span>EXPECTED EFFECT</span><strong>${result.expected}</strong></div><div><span>WHY</span><strong>${result.why}</strong></div><div><span>RAW CALL</span><strong>${result.contract}<br>${result.selector}</strong></div></div><p class="panel-foot">Depth: Simple → Curious → Technical → Raw. This explanation is deterministic wallet interpretation, not a claim that the transaction executed.</p></div>`; }
function stateDiff() { const result = explanation(readCandidate()); const amount = result.known ? result.amount : 0; return { result, rows: [{ label: 'WQUAI', before: 'current balance', delta: amount ? `−${amount} WQUAI` : 'unknown', certainty: result.known ? 'predicted' : 'blocked' }, { label: 'native QUAI', before: 'current balance', delta: amount ? `+${amount} QUAI` : 'unknown', certainty: result.known ? 'predicted' : 'blocked' }, { label: 'gas', before: 'not queried', delta: result.known ? 'reserved, exact fee unknown' : 'unknown', certainty: 'uncertain' }] }; }
function renderSimulation() { const diff = stateDiff(); teachingOutput.innerHTML = `<div class="simulation-card ${diff.result.known ? 'known' : 'unknown'}"><div class="explanation-status">${diff.result.known ? 'PRE-SIGN PREDICTION' : 'PREDICTION BLOCKED'}</div><h3>${diff.result.known ? 'What should change if you approve?' : 'No safe prediction available'}</h3>${diff.rows.map((row) => `<div class="diff-row"><strong>${row.label}</strong><span>${row.before}</span><b>${row.delta}</b><em>${row.certainty}</em></div>`).join('')}<p class="uncertainty">⚠ Uncertainty is part of the result: this demo does not execute a call, estimate a fee, or sign. The expected effect is conditional on the contract, caller, and calldata remaining as shown.</p></div>`; }
function askQuai(question) { const q = question.trim().toLowerCase(); if (!q) return { answer: 'Ask a question about the observed address or the WQUAI operation.', facts: ['No query was provided.'], source: 'LOCAL INPUT', interpretation: 'No interpretation was attempted.' }; if (q.includes('wquai') && (q.includes('why') || q.includes('what'))) return { answer: 'WQUAI is the wrapped-QUAI asset visible in this address context. The wallet can show its indexed balance, but this screen does not prove who wrapped it, why it arrived, or that it can be withdrawn successfully.', facts: ['The current asset view labels WQUAI as a fungible token.', 'The balance and transfer records come from QuaiScan account endpoints.'], source: 'QUAIScan · tokenlist + tokentx', interpretation: 'The likely explanation is that WQUAI represents a wrapped form of native QUAI; provenance of acquisition remains unknown.' }; if (q.includes('withdraw') || q.includes('unwrap')) return { answer: 'The teaching lab recognizes withdraw(uint256) as a candidate WQUAI operation. It predicts WQUAI down and native QUAI up, but this answer is not evidence that a call would succeed for this account or contract state.', facts: ['Selector: 0x2e1a7d4d.', 'Demo 3 predicts a conditional state change; no call was executed.'], source: 'LOCAL WALLET INTERPRETATION', interpretation: 'Candidate intent is separated from execution evidence.' }; return { answer: 'No bounded answer is available from the current wallet context.', facts: ['This wallet has no indexed evidence for that question.'], source: 'NO SOURCE', interpretation: 'The correct result is uncertainty, not a generic ecosystem answer.' }; }
function renderAsk() { const result = askQuai(askInput.value); askOutput.innerHTML = `<div class="ask-card"><div class="explanation-status">CONTEXT-AWARE ANSWER</div><h3>${escapeHtml(result.answer)}</h3><div class="ask-evidence"><div><span>ON-CHAIN FACT</span><p>${result.facts.map(escapeHtml).join('<br>')}</p></div><div><span>ECOSYSTEM SOURCE</span><p>${escapeHtml(result.source)}</p></div><div><span>MODEL INTERPRETATION</span><p>${escapeHtml(result.interpretation)}</p></div></div><p class="panel-foot">Bounded local teaching mode. No private data, external model call, or transaction action was used.</p></div>`; }
function currentPattern() { return { contract: cachedContractInput.value.trim(), selector: cachedSelectorInput.value.trim().toLowerCase(), function: 'withdraw(uint256)', expectedEffects: ['WQUAI decreases', 'native QUAI increases'], permission: 'caller must satisfy the contract and chain conditions' }; }
function readCachedPattern() { try { return JSON.parse(localStorage.getItem(CACHE_KEY) || 'null'); } catch { return null; } }
function renderCacheResult(kind, detail) { const recognized = kind === 'recognized'; cacheOutput.innerHTML = `<div class="cache-card ${recognized ? 'known' : 'unknown'}"><div class="explanation-status">${recognized ? 'RECOGNIZED OPERATION' : 'RE-UNDERSTAND REQUIRED'}</div><h3>${recognized ? 'The cached pattern still matches.' : 'Familiarity invalidated.'}</h3><p>${escapeHtml(detail)}</p><div class="ask-evidence"><div><span>CACHED ASSUMPTIONS</span><p>contract · selector · function · expected effects · permission</p></div><div><span>VALIDATION MODE</span><p>local comparison only; live chain state remains authoritative</p></div></div><p class="panel-foot">A cache reduces repeated explanation cost. It does not authorize signing or replace current verification.</p></div>`; }
function rememberPattern() { const pattern = currentPattern(); if (!isAddress(pattern.contract) || !/^0x[0-9a-f]{8}$/.test(pattern.selector)) { renderCacheResult('invalid', 'Pattern not stored: contract or selector has an invalid shape.'); return; } localStorage.setItem(CACHE_KEY, JSON.stringify(pattern)); renderCacheResult('recognized', `Stored ${pattern.function} at ${shortAddress(pattern.contract)}. Future matches will be compared against these assumptions.`); }
function comparePattern() { const cached = readCachedPattern(); if (!cached) { renderCacheResult('invalid', 'No cached pattern exists. Understand the operation before asking for reuse.'); return; } const current = currentPattern(); const changed = ['contract', 'selector', 'function', 'permission'].filter((key) => cached[key] !== current[key]); const effectsChanged = JSON.stringify(cached.expectedEffects) !== JSON.stringify(current.expectedEffects); if (effectsChanged) changed.push('expected effects'); if (!changed.length) renderCacheResult('recognized', `Matched the remembered ${cached.function} pattern at ${shortAddress(cached.contract)}.`); else renderCacheResult('invalid', `The changed assumption is: ${changed.join(', ')}. The wallet will not reuse the cached explanation.`); }
function nftContract() { const value = nftContractInput.value.trim(); if (!isAddress(value)) throw new Error('Collection contract must be a valid 0x address'); return value; }
function renderNftObject() { try { const contract = nftContract(); const tokenId = nftTokenIdInput.value.trim(); if (!tokenId) throw new Error('Token ID is required'); nftOutput.innerHTML = `<div class="nft-card"><div class="explanation-status">NFT OBJECT · INDEXED PROVENANCE</div><h3>Token #${escapeHtml(tokenId)}</h3><div class="ask-evidence"><div><span>COLLECTION CONTRACT</span><p class="mono">${escapeHtml(contract)}</p></div><div><span>PROVENANCE</span><p>Ownership and transfer history require the indexed collection record.</p></div><div><span>METADATA</span><p>No metadata was fabricated. The collection contract is the current object anchor.</p></div></div><p class="panel-foot">Object view is read-only. Next step: query the current holder network.</p></div>`; } catch (cause) { nftOutput.innerHTML = `<p class="uncertainty">NFT object not opened: ${escapeHtml(cause.message)}</p>`; } }
async function findOthers() { try { const contract = nftContract(); const holders = await scan('getTokenHolders', contract); const rows = Array.isArray(holders) ? holders : []; const visible = rows.slice(0, 20).map((holder) => `<div class="holder-row"><span class="mono">${escapeHtml(holder.address || holder.holderAddress || 'unknown')}</span><strong>${escapeHtml(holder.value || holder.amount || '—')}</strong></div>`).join(''); nftOutput.innerHTML = `<div class="nft-card"><div class="explanation-status">HOLDER NETWORK · QUAISCAN READ</div><h3>${rows.length ? `${rows.length} current holder records` : 'No holder records returned'}</h3>${visible || '<p class="hint">The indexer returned no current records for this contract. That is not proof that the collection has no holders.</p>'}<p class="panel-foot">Source: QuaiScan token/getTokenHolders. This is a current holder list, not a social graph or permission to contact anyone.</p></div>`; } catch (cause) { nftOutput.innerHTML = `<p class="uncertainty">Holder network unavailable: ${escapeHtml(cause.message)}</p>`; } }
const policyMessages = [{ id: 'm1', sender: 'current-holder', text: 'A new collector just joined our test network.', holder: true, link: false, mutual: true }, { id: 'm2', sender: 'current-holder', text: 'Summary: three collection notes, one shared project.', holder: true, link: false, mutual: false }, { id: 'm3', sender: 'non-holder', text: 'Urgent link: claim your reward now https://example.invalid', holder: false, link: true, mutual: false }];
function policyDecision(message) { const rules = []; if (document.querySelector('#holder-required').checked && !message.holder) rules.push('current holder required'); if (document.querySelector('#links-quarantined').checked && message.link) rules.push('links quarantined'); if (document.querySelector('#duplicates-suppressed').checked && policyMessages.some((other) => other.id !== message.id && other.text === message.text)) rules.push('duplicates suppressed'); if (rules.length) return { outcome: 'QUARANTINED', rules }; return { outcome: message.text.startsWith('Summary:') ? 'SUMMARIZED' : 'DELIVERED', rules: message.mutual && document.querySelector('#mutual-prioritized').checked ? ['mutual-network holder prioritized'] : ['no blocking rule matched'] }; }
function renderPolicy() { const rows = policyMessages.map((message) => { const decision = policyDecision(message); return `<div class="policy-row"><div><strong>${escapeHtml(message.sender)}</strong><span>${escapeHtml(message.text)}</span></div><b class="policy-${decision.outcome.toLowerCase()}">${decision.outcome}</b><button class="secondary why-filtered" data-message="${message.id}" type="button">Why was this filtered?</button><em>${escapeHtml(decision.rules.join('; '))}</em></div>`; }).join(''); policyOutput.innerHTML = `<div class="policy-card"><div class="explanation-status">AUDITABLE POLICY OUTCOMES</div><h3>Three messages. Three visible decisions.</h3>${rows}<p class="panel-foot">Local test fixtures only. Delivery is not contact permission, on-chain ownership is not identity, and every decision can be overridden by the wallet holder.</p></div>`; document.querySelectorAll('.why-filtered').forEach((button) => button.addEventListener('click', () => { const message = policyMessages.find((item) => item.id === button.dataset.message); const decision = policyDecision(message); button.parentElement.querySelector('em').textContent = `Why: ${decision.rules.join('; ')}. Override remains available.`; })); }
function renderSandbox(active) { if (!active) { sandboxOutput.innerHTML = '<p class="hint">No learner credential. Nothing here touches the chain.</p>'; return; } sandboxOutput.innerHTML = '<div class="sandbox-card"><div class="explanation-status">TEMPORARY LEARNER NFT · SIMULATED NETWORK</div><h3>Learner #LOCAL-001 is ready to practice</h3><div class="sandbox-steps"><div><b>01</b><span>Credential issued locally</span><small>Not minted. Not transferable. Expires when this tab is reset.</small></div><div><b>02</b><span>Enter simulated network</span><small>Practice access rules without real membership.</small></div><div><b>03</b><span>Route a red-team message</span><small>Bounded personas: promoter, link dropper, urgency sender, collaborator, network bridge.</small></div><div><b>04</b><span>Inspect simulated transaction</span><small>Accept only after identifying the recipient, value, and permission boundary.</small></div></div><button id="sandbox-route" type="button">Route simulated red-team message</button><p class="panel-foot">This temporary learner NFT cannot grant real BIPU membership. Completed exercises are tracked only in this tab; no claim about understanding is inferred.</p></div>'; document.querySelector('#sandbox-route').addEventListener('click', () => { document.querySelector('#sandbox-route').insertAdjacentHTML('afterend', '<p class="uncertainty sandbox-result">QUARANTINED · urgency sender + external link. Reason is visible; no message was sent.</p>'); }); }
function provider() { return window.pelagus || window.ethereum || null; }
async function connectWallet() { const candidate = provider(); if (!candidate) { signingOutput.innerHTML = '<p class="uncertainty">No compatible EVM provider was detected. Install/connect a wallet before attempting Demo 4.</p>'; return; } try { const accounts = await candidate.request({ method: 'eth_requestAccounts' }); const account = accounts?.[0]; if (!account) throw new Error('Provider returned no account'); connectedProvider = candidate; prepareRequestButton.disabled = false; connectWalletButton.textContent = `Connected ${shortAddress(account)}`; signingOutput.innerHTML = `<p class="hint">Provider connected: ${escapeHtml(shortAddress(account))}. BIPU has no private-key access.</p>`; } catch (cause) { signingOutput.innerHTML = `<p class="uncertainty">Connection cancelled or failed: ${escapeHtml(cause.message)}</p>`; } }
function buildExplainedRequest() { const recipient = document.querySelector('#recipient').value.trim(); const amount = Number(document.querySelector('#send-amount').value); if (!connectedProvider) throw new Error('Connect a compatible wallet first'); if (!isAddress(recipient)) throw new Error('Recipient must be a valid 0x address'); if (!Number.isFinite(amount) || amount <= 0) throw new Error('Amount must be greater than zero'); return { from: null, to: recipient, value: `0x${BigInt(Math.round(amount * 1e18)).toString(16)}` }; }
async function prepareRequest() { try { explainedRequest = buildExplainedRequest(); const accounts = await connectedProvider.request({ method: 'eth_accounts' }); explainedRequest.from = accounts?.[0]; if (!explainedRequest.from) throw new Error('Provider returned no active account'); signingOutput.innerHTML = `<div class="explanation-card known"><div class="explanation-status">EXPLAINED REQUEST · PROVIDER-GATED</div><h3>Send ${escapeHtml(document.querySelector('#send-amount').value)} QUAI</h3><div class="explanation-grid"><div><span>FROM</span><strong>${escapeHtml(shortAddress(explainedRequest.from))}</strong></div><div><span>TO</span><strong>${escapeHtml(shortAddress(explainedRequest.to))}</strong></div><div><span>VALUE</span><strong>${escapeHtml(document.querySelector('#send-amount').value)} QUAI</strong></div><div><span>RAW VALUE</span><strong>${explainedRequest.value}</strong></div></div><button id="approve-send" type="button">Approve &amp; send</button><p class="panel-foot">Provider-gated. The browser wallet will show the final prompt. BIPU cannot sign silently.</p></div>`; document.querySelector('#approve-send').addEventListener('click', approveAndSend); } catch (cause) { signingOutput.innerHTML = `<p class="uncertainty">Request not prepared: ${escapeHtml(cause.message)}</p>`; } }
async function approveAndSend() { if (!connectedProvider || !explainedRequest) return; const button = document.querySelector('#approve-send'); button.disabled = true; button.textContent = 'Waiting for provider…'; try { const hash = await connectedProvider.request({ method: 'eth_sendTransaction', params: [explainedRequest] }); signingOutput.innerHTML = `<p class="hint">Provider accepted the request. Transaction hash: <span class="mono">${escapeHtml(hash)}</span>. Refresh chain state to reconcile the result.</p>`; } catch (cause) { button.disabled = false; button.textContent = 'Approve & send'; signingOutput.innerHTML += `<p class="uncertainty">Not sent: ${escapeHtml(cause.message)}</p>`; } }
async function rpc(method, params = []) {
  const response = await fetch(RPC_URL, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', method, params, id: Date.now() }) });
  if (!response.ok) throw new Error(`RPC responded with HTTP ${response.status}`);
  const payload = await response.json(); if (payload.error) throw new Error(payload.error.message || 'Quai RPC error'); return payload.result;
}
async function scan(action, address, extra = '') {
  const response = await fetch(`${SCAN_URL}?module=account&action=${action}&address=${encodeURIComponent(address)}${extra}`);
  if (!response.ok) throw new Error(`QuaiScan responded with HTTP ${response.status}`);
  const payload = await response.json();
  if (payload.status === '0' && action !== 'tokenlist') throw new Error(payload.message || 'QuaiScan returned no data');
  return payload.result || [];
}
function normalizedAssets(nativeWei, tokenList) {
  return [{ type: 'native', symbol: 'QUAI', name: 'Quai', contract: null, decimals: 18, balance: nativeWei, source: 'account/balance' }, ...tokenList.map((token) => ({ type: token.type === 'ERC-721' ? 'nft' : 'fungible', symbol: token.symbol || '—', name: token.name || 'Unnamed token', contract: token.contractAddress, decimals: Number(token.decimals || 0), balance: big(token.balance || 0), source: 'account/tokenlist' }))];
}
function activityLabel(item, address) {
  const self = address.toLowerCase(); const from = (item.from || '').toLowerCase(); const to = (item.to || '').toLowerCase();
  return from === self ? 'Sent' : to === self ? 'Received' : 'Observed';
}
function render({ address, nativeWei, assets, transfers, chainId, blockNumber, observedAt }) {
  const assetRows = assets.map((asset) => `<div class="asset-row"><div class="asset-icon ${asset.type}">${asset.type === 'native' ? 'Q' : asset.type === 'nft' ? 'N' : 'T'}</div><div class="asset-main"><strong>${escapeHtml(asset.symbol)}</strong><span>${escapeHtml(asset.name)}</span></div><div class="asset-balance">${formatUnits(asset.balance, asset.decimals)} <small>${escapeHtml(asset.symbol)}</small></div><div class="asset-meta"><span>${asset.type.toUpperCase()}</span><span>${asset.contract ? escapeHtml(shortAddress(asset.contract)) : 'native ledger'}</span></div></div>`).join('');
  const activityRows = transfers.slice(0, 5).map((item) => `<div class="activity-row"><div class="activity-direction ${activityLabel(item, address).toLowerCase()}">${activityLabel(item, address) === 'Received' ? '↓' : '↑'}</div><div class="activity-main"><strong>${activityLabel(item, address)} ${escapeHtml(item.tokenSymbol || 'token')}</strong><span>${escapeHtml(shortAddress(item.hash || item.transactionHash))}</span></div><div class="activity-value">${formatUnits(big(item.value || 0), Number(item.tokenDecimal || 18))} ${escapeHtml(item.tokenSymbol || '')}<small>block ${Number(item.blockNumber).toLocaleString()}</small></div></div>`).join('') || '<div class="no-activity">No token transfer events were returned for this address.</div>';
  state.innerHTML = `<div class="observation"><div class="state-head"><div><div class="metric-label">NORMALIZED WALLET STATE</div><h2>${escapeHtml(shortAddress(address))}</h2></div><div class="network-pill">CYPRUS-1 · CHAIN ${big(chainId).toString()}</div></div><div class="content-grid"><article class="panel assets"><div class="panel-head"><div><div class="metric-label">ASSETS</div><h3>${assets.length} normalized ${assets.length === 1 ? 'asset' : 'assets'}</h3></div><span class="source-chip">QuaiScan · tokenlist</span></div>${assetRows}<p class="panel-foot">Native QUAI is represented separately from fungible tokens. Contract addresses are not inferred.</p></article><article class="panel activity"><div class="panel-head"><div><div class="metric-label">RECENT ACTIVITY</div><h3>${transfers.length ? `${Math.min(transfers.length, 5)} token events` : 'No token events'}</h3></div><span class="source-chip">QuaiScan · tokentx</span></div>${activityRows}<p class="panel-foot">Events are normalized into direction, token, amount, and block. Calldata remains untouched.</p></article></div><div class="refresh-line"><span>Observed ${observedAt.toLocaleTimeString()} · block ${Number(blockNumber).toLocaleString()}</span><button id="refresh" type="button">↻ Refresh live state</button></div></div>`;
  document.querySelector('#refresh').addEventListener('click', observe);
}
async function observe() {
  const address = addressInput.value.trim(); error.hidden = true;
  if (!isAddress(address)) { error.textContent = 'That is not a valid EVM address. Expected 0x followed by 40 hexadecimal characters.'; error.hidden = false; return; }
  observeButton.disabled = true; observeButton.textContent = 'Reading…'; state.innerHTML = '<div class="empty-state"><div class="pulse-ring"></div><p>Reading native state, assets, and activity…</p></div>';
  try {
    const [nativeWei, chainId, blockNumber, tokenList, transfers] = await Promise.all([scan('balance', address), rpc('quai_chainId'), rpc('quai_blockNumber'), scan('tokenlist', address), scan('tokentx', address, '&page=1&offset=5&sort=desc')]);
    render({ address, nativeWei: big(nativeWei), assets: normalizedAssets(big(nativeWei), tokenList), transfers: Array.isArray(transfers) ? transfers : [], chainId, blockNumber, observedAt: new Date() });
  } catch (cause) { error.textContent = `Could not normalize this address: ${cause.message}`; error.hidden = false; state.innerHTML = '<div class="empty-state"><div class="pulse-ring"></div><p>Observation failed. No synthetic balances were substituted.</p></div>'; }
  finally { observeButton.disabled = false; observeButton.innerHTML = 'Load state <span>↗</span>'; }
}
observeButton.addEventListener('click', observe); addressInput.addEventListener('keydown', (event) => { if (event.key === 'Enter') observe(); });
document.querySelector('#explain').addEventListener('click', renderExplanation);
document.querySelector('#simulate').addEventListener('click', renderSimulation);
connectWalletButton.addEventListener('click', connectWallet);
prepareRequestButton.addEventListener('click', prepareRequest);
askButton.addEventListener('click', renderAsk);
askInput.addEventListener('keydown', (event) => { if (event.key === 'Enter') renderAsk(); });
rememberPatternButton.addEventListener('click', rememberPattern);
comparePatternButton.addEventListener('click', comparePattern);
openNftButton.addEventListener('click', renderNftObject);
findOthersButton.addEventListener('click', findOthers);
runPolicyButton.addEventListener('click', renderPolicy);
issueLearnerButton.addEventListener('click', () => renderSandbox(true));
resetSandboxButton.addEventListener('click', () => renderSandbox(false));
