import { explainOperation, predictOperation, WQUAI_CONTRACT } from '../core/operation.js';
import { validateNftRequest } from '../core/nft.js';
import { POLICY_MESSAGES, policyReport } from '../core/policy.js';
import { LEARNER_ID, PRACTICE_STEPS, issueLearner, routePracticeMessage } from '../core/sandbox.js';

async function message(payload) { return chrome.runtime.sendMessage(payload); }
const title = document.querySelector('#context-title');
const copy = document.querySelector('#context-copy');
const address = document.querySelector('#address');
const observeButton = document.querySelector('#observe');
const observation = document.querySelector('#observation');
const selector = document.querySelector('#selector');
const amount = document.querySelector('#amount');
const operationOutput = document.querySelector('#operation-output');
const connectProviderButton = document.querySelector('#connect-provider');
const providerStatus = document.querySelector('#provider-status');
const prepareTransferButton = document.querySelector('#prepare-transfer');
const signingOutput = document.querySelector('#signing-output');
let providerAccount = null;
let explainedTransaction = null;
let observedContext = {};
const phaseCopy = { observe: ['No object selected', 'Phase 2 observes native QUAI. Explain and Predict attach to this same wallet context.'], understand: ['Operation understanding active', 'Explain and Predict are deterministic and remain separate from signing.'], network: ['Network mode reserved', 'NFT holders and policy controls will attach to an object in a later slice.'], practice: ['Practice mode reserved', 'The temporary learner sandbox will move here in a later slice.'], graduate: ['Graduation mode reserved', 'Observable gates will move here in a later slice.'] };
function formatUnits(hexWei, decimals = 18) { const value = BigInt(hexWei || 0); const scale = 10n ** BigInt(decimals); const whole = value / scale; const fraction = (value % scale).toString().padStart(decimals, '0').slice(0, 4).replace(/0+$/, ''); return `${whole.toLocaleString()}${fraction ? `.${fraction}` : ''}`; }
function escape(value) { return String(value).replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char])); }
function renderObservation(data) { observedContext = data; const tokens = Array.isArray(data.tokenList) ? data.tokenList : []; const transfers = Array.isArray(data.transfers) ? data.transfers : []; const assets = [{ symbol: 'QUAI', name: 'Native QUAI', balance: formatUnits(data.balance), type: 'native' }, ...tokens.map((token) => ({ symbol: token.symbol || '—', name: token.name || 'Unnamed token', balance: formatUnits(token.balance, Number(token.decimals || 0)), type: token.type === 'ERC-721' ? 'NFT' : 'TOKEN' }))]; const assetRows = assets.map((asset) => `<div class="asset-row"><strong>${escape(asset.symbol)}</strong><span>${escape(asset.name)}</span><b>${asset.balance}</b><em>${asset.type}</em></div>`).join(''); const activityRows = transfers.slice(0, 5).map((item) => `<div class="activity-row"><strong>${escape(item.tokenSymbol || 'token')}</strong><span>${escape(item.from || 'unknown')} → ${escape(item.to || 'unknown')}</span><b>block ${Number(item.blockNumber || 0).toLocaleString()}</b></div>`).join('') || '<p class="muted">No token transfer events returned.</p>'; observation.innerHTML = `<div class="observation-result"><div class="metric"><span>NETWORK</span><strong>Cyprus-1 · chain ${BigInt(data.chainId).toString()}</strong></div><div class="metric"><span>OBSERVED BLOCK</span><strong>${BigInt(data.blockNumber).toLocaleString()}</strong></div><h3>Normalized assets <small>${assets.length}</small></h3>${assetRows}<h3>Recent activity <small>${transfers.length}</small></h3>${activityRows}<p class="small">Sources: <span class="mono">${data.sources.rpc}</span> · QuaiScan tokenlist + tokentx. Observed ${new Date(data.observedAt).toLocaleTimeString()}.</p></div>`; title.textContent = 'Wallet state normalized'; copy.textContent = `Read-only state for ${data.address}. Native QUAI, token inventory, and transfer events are separated by source.`; }
async function observe() { observeButton.disabled = true; observeButton.textContent = 'Reading…'; observation.innerHTML = '<p class="muted">Reading Cyprus-1…</p>'; const response = await message({ type: 'OBSERVE_ADDRESS', address: address.value }); if (response?.ok) renderObservation(response.observation); else observation.innerHTML = `<p class="observation-error">Observation failed: ${response?.error || 'unknown error'}</p>`; observeButton.disabled = false; observeButton.textContent = 'Observe'; }
function renderExplanation() { const result = explainOperation({ selector: selector.value, amount: amount.value }); operationOutput.innerHTML = `<div class="operation-result"><div class="label">${result.known ? 'RECOGNIZED PATTERN' : 'UNDERSTANDING BLOCKED'}</div><h3>${result.title}</h3><div class="operation-grid"><div><span>INTENT</span><strong>${result.intent}</strong></div><div><span>EXPECTED EFFECT</span><strong>${result.expected}</strong></div><div><span>WHY</span><strong>${result.why}</strong></div><div><span>RAW CALL</span><strong class="mono">${result.contract}<br>${result.selector}</strong></div></div><p class="small">Deterministic local interpretation. This does not execute, estimate gas, sign, or broadcast.</p></div>`; }
function renderPrediction() { const prediction = predictOperation({ selector: selector.value, amount: amount.value }); operationOutput.innerHTML = `<div class="operation-result"><div class="label">${prediction.result.known ? 'PRE-SIGN PREDICTION' : 'PREDICTION BLOCKED'}</div><h3>${prediction.result.known ? 'What should change if you approve?' : 'No safe prediction available'}</h3>${prediction.rows.map((row) => `<div class="diff-row"><strong>${row.label}</strong><span>current state</span><b>${row.delta}</b><em>${row.certainty}</em></div>`).join('')}<p class="small">Conditional only. Current balances, contract state, caller, and gas are not verified by this exercise.</p></div>`; }
for (const button of document.querySelectorAll('.mode')) button.addEventListener('click', async () => { document.querySelector('.mode.active')?.classList.remove('active'); button.classList.add('active'); const phase = button.dataset.phase; [title.textContent, copy.textContent] = phaseCopy[phase]; await message({ type: 'SET_PHASE', phase }); });
observeButton.addEventListener('click', observe);
address.addEventListener('keydown', (event) => { if (event.key === 'Enter') observe(); });
document.querySelector('#explain').addEventListener('click', renderExplanation);
document.querySelector('#predict').addEventListener('click', renderPrediction);
async function askQuai() { const output = document.querySelector('#ask-output'); const question = document.querySelector('#question').value; output.innerHTML = '<p class="muted">Checking bounded wallet context…</p>'; const token = (observedContext.tokenList || []).find((item) => String(item.symbol || '').toUpperCase() === 'WQUAI'); const response = await message({ type: 'ASK_QUAI', question, selector: selector.value, wquaiBalance: token?.balance ? formatUnits(token.balance, Number(token.decimals || 18)) : '0' }); if (!response?.ok) { output.innerHTML = `<p class="observation-error">Ask failed: ${response?.error || 'unknown error'}</p>`; return; } output.innerHTML = `<div class="ask-result"><h3>${response.answer.supported ? 'Bounded answer' : 'Uncertainty preserved'}</h3>${response.answer.evidence.map((item) => `<div class="evidence-row"><span>${item.type}</span><p>${item.text}</p></div>`).join('')}</div>`; }
document.querySelector('#ask').addEventListener('click', askQuai);
document.querySelector('#question').addEventListener('keydown', (event) => { if (event.key === 'Enter') askQuai(); });
function currentOperation() { const explanation = explainOperation({ selector: selector.value, amount: amount.value }); return { contract: WQUAI_CONTRACT, selector: selector.value, expected: explanation.expected }; }
function showCache(comparison) { const changed = comparison.changed?.length ? ` Changed: ${comparison.changed.join(', ')}.` : ''; document.querySelector('#cache-output').innerHTML = `<div class="cache-result"><strong>${comparison.status}</strong><p class="small">${comparison.status === 'Recognized operation' ? 'Familiarity matches the remembered assumptions.' : comparison.status === 'Re-understand required' ? `A remembered assumption no longer matches.${changed}` : 'Remember a pattern before validating it.'}</p><p class="small">Local familiarity never replaces live chain verification or authorizes signing.</p></div>`; }
document.querySelector('#remember-operation').addEventListener('click', async () => { const response = await message({ type: 'REMEMBER_OPERATION', operation: currentOperation() }); if (response?.ok) showCache({ status: 'Pattern remembered', changed: [] }); else showCache({ status: `Remember failed: ${response?.error || 'unknown error'}`, changed: [] }); });
document.querySelector('#validate-operation').addEventListener('click', async () => { const response = await message({ type: 'VALIDATE_OPERATION', operation: currentOperation() }); if (response?.ok) showCache(response.comparison); else showCache({ status: `Validation failed: ${response?.error || 'unknown error'}`, changed: [] }); });
function nftRequest() { return validateNftRequest(document.querySelector('#nft-contract').value, document.querySelector('#nft-token').value); }
function nftError(error) { document.querySelector('#nft-output').innerHTML = `<p class="observation-error">NFT request blocked: ${escape(error.message || error)}</p>`; }
document.querySelector('#inspect-nft').addEventListener('click', () => { try { const request = nftRequest(); document.querySelector('#nft-output').innerHTML = `<div class="nft-result"><div class="label">READ-ONLY OBJECT</div><h3>Token #${request.tokenId}</h3><p class="mono">Collection ${request.contract}</p><p class="small">Identity fields are recorded locally for this view. No ownership is inferred until the current indexer is queried.</p></div>`; } catch (error) { nftError(error); } });
document.querySelector('#find-holders').addEventListener('click', async () => { let request; try { request = nftRequest(); } catch (error) { nftError(error); return; } const output = document.querySelector('#nft-output'); output.innerHTML = '<p class="muted">Querying current holder index…</p>'; const response = await message({ type: 'NFT_HOLDERS', ...request }); if (!response?.ok) { nftError(new Error(response?.error || 'holder lookup failed')); return; } const result = response.result; const rows = result.holders.map((holder) => `<div class="holder-row"><span class="mono">${escape(holder.address || holder.holder || holder)}</span><b>${escape(holder.balance || holder.quantity || '1')}</b></div>`).join(''); output.innerHTML = `<div class="nft-result"><div class="label">CURRENT INDEXER DATA</div><h3>${result.found ? `${result.holders.length} holder record${result.holders.length === 1 ? '' : 's'}` : 'No holder records'}</h3>${rows || `<p class="muted">${result.message}</p>`}<p class="small">${result.message}</p><p class="small mono">Source: ${escape(result.source)}</p></div>`; });
document.querySelector('#run-policy').addEventListener('click', () => { const rules = { network: document.querySelector('#policy-network').value, holderRequired: document.querySelector('#policy-holder').checked, linksQuarantined: document.querySelector('#policy-links').checked }; const rows = policyReport(POLICY_MESSAGES, rules).map(({ message, decision }) => `<div class="policy-row"><div><strong>${escape(message.sender)}</strong><span>${escape(message.text)}</span></div><b class="policy-${decision.outcome.toLowerCase()}">${decision.outcome}</b><button class="secondary why-filtered" data-message="${message.id}" type="button">Why?</button><em>${escape(decision.reasons.join('; '))}</em></div>`).join(''); const output = document.querySelector('#policy-output'); output.innerHTML = `<div class="policy-result"><div class="label">AUDITABLE POLICY OUTCOMES</div><h3>Four fixtures. Visible decisions.</h3>${rows}<p class="small">No message was sent. Network matching is a filter, not endorsement, safety, liquidity, custody, or contact permission.</p></div>`; output.querySelectorAll('.why-filtered').forEach((button) => button.addEventListener('click', () => { const row = policyReport(POLICY_MESSAGES, rules).find((item) => item.message.id === button.dataset.message); button.parentElement.querySelector('em').textContent = `Why: ${row.decision.reasons.join('; ')}.`; })); });
document.querySelector('#issue-learner').addEventListener('click', () => { const learner = issueLearner(); const steps = PRACTICE_STEPS.map(([number, title, note]) => `<div class="sandbox-step"><b>${number}</b><span>${title}</span><small>${note}</small></div>`).join(''); document.querySelector('#sandbox-output').innerHTML = `<div class="sandbox-result"><div class="label">TEMPORARY LEARNER · SIMULATED NETWORK</div><h3>${learner.id} is ready to practice</h3><div class="sandbox-steps">${steps}</div><button id="route-practice" type="button">Route red-team fixture</button><p class="small">Issued locally. Not minted, transferable, or evidence of understanding.</p></div>`; document.querySelector('#route-practice').addEventListener('click', () => { const result = routePracticeMessage(); document.querySelector('#route-practice').insertAdjacentHTML('afterend', `<p class="sandbox-route"><strong>${result.outcome}</strong> · ${result.reasons.join(' + ')}. No message was sent.</p>`); }); });
document.querySelector('#reset-sandbox').addEventListener('click', () => { document.querySelector('#sandbox-output').innerHTML = '<p class="muted">No learner credential. Nothing here touches the chain.</p>'; });
 connectProviderButton.addEventListener('click', async () => { connectProviderButton.disabled = true; providerStatus.textContent = 'Requesting account from active-page provider…'; const response = await message({ type: 'CONNECT_PROVIDER' }); if (response?.ok && response.account) { providerAccount = response.account; providerStatus.textContent = `Connected ${providerAccount}. BIPU never receives private keys.`; prepareTransferButton.disabled = false; } else { providerStatus.textContent = `Connection blocked: ${response?.error || 'no compatible provider detected'}`; } connectProviderButton.disabled = false; });
prepareTransferButton.addEventListener('click', () => { const recipient = document.querySelector('#recipient').value.trim(); const amount = Number(document.querySelector('#send-amount').value); if (!providerAccount) { signingOutput.innerHTML = '<p class="observation-error">Connect a provider first.</p>'; return; } if (!/^0x[a-fA-F0-9]{40}$/.test(recipient) || !Number.isFinite(amount) || amount <= 0) { signingOutput.innerHTML = '<p class="observation-error">Request blocked: recipient or amount is invalid.</p>'; return; } explainedTransaction = { from: providerAccount, to: recipient, value: `0x${BigInt(Math.round(amount * 1e18)).toString(16)}` }; signingOutput.innerHTML = `<div class="signing-result"><div class="label">EXPLAINED REQUEST · NOT SENT</div><div class="signing-grid"><div><span>FROM</span><strong>${providerAccount}</strong></div><div><span>TO</span><strong>${recipient}</strong></div><div><span>VALUE</span><strong>${amount} QUAI</strong></div><div><span>RAW VALUE</span><strong>${explainedTransaction.value}</strong></div></div><button id="approve-send" type="button">Approve &amp; send</button><p class="small">This is the only control that can request provider signing. The browser wallet will show the final prompt.</p></div>`; document.querySelector('#approve-send').addEventListener('click', async () => { const approve = document.querySelector('#approve-send'); approve.disabled = true; approve.textContent = 'Waiting for provider…'; const response = await message({ type: 'SEND_TRANSACTION', transaction: explainedTransaction }); if (response?.ok) signingOutput.innerHTML = `<p class="small">Provider accepted the request. Transaction hash: <span class="mono">${response.hash}</span>. Refresh state to reconcile.</p>`; else { approve.disabled = false; approve.textContent = 'Approve & send'; signingOutput.insertAdjacentHTML('beforeend', `<p class="observation-error">Not sent: ${response?.error || 'provider rejected request'}</p>`); } }); });
